### ISSUE TITLE
Hi, smartdevcode.

### ISSUE THREAD

**Issue by fullsmartdev** [smartdevcode/interaction#1]
I am really interested in your interaction app. Actually there are several voice to speech recognizer in Github repos but on my end, most of them doesn't work well. 
Could you let me know what third-party lib you used for it?
Best Regards

**Comment by smartdevcode** [comment]
@fullsmartdev Thanks for your consideration.
Please use [Vosk model](https://alphacephei.com/vosk/models). In my experience, it is good to me and it works well both online and offline.

**Comment by fullsmartdev** [comment]
@smartdevcode Wow, awesome. I will try on my end.

**Comment by smartdevcode** [comment]
Brilliant. That work on my end. Thanks for your kind help. :)

**Comment by fullsmartdev** [comment]
Brilliant. That work on my end. Thanks for your kind help. :)
